[phases.setup]
nixPkgs = ["python310"]

[phases.install]  
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
